export const phrasalVerbsModule = {
  metadata: { id: "phrasal-verbs", title: "Phrasal Verbs", description: "Practise donor-sourced phrasal verbs in practical contexts.", levelRange: 'A2-C1' },
  topics: [
    {
      "id": "donor-import",
      "title": "Authoritative Donor Import"
    }
  ],
  questions: [
    {
      "id": "phrasal-verbs-001",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: He stopped trying after a few attempts.",
      "options": [
        "give up",
        "pick up",
        "catch up with",
        "keep up with"
      ],
      "answer": "give up",
      "explanation": "give up is the donor phrasal verb for: He stopped trying after a few attempts.",
      "translation": "Он сдался после нескольких попыток.",
      "example": "He gave up after a few tries.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 1,
      "donorKey": "give up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-002",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: I lifted it from the floor.",
      "options": [
        "pick up",
        "catch up with",
        "keep up with",
        "leave out"
      ],
      "answer": "pick up",
      "explanation": "pick up is the donor phrasal verb for: I lifted it from the floor.",
      "translation": "Я поднял это с пола.",
      "example": "I picked it up from the floor.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 2,
      "donorKey": "pick up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-003",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: We need to reach the group.",
      "options": [
        "catch up with",
        "keep up with",
        "leave out",
        "drop out of"
      ],
      "answer": "catch up with",
      "explanation": "catch up with is the donor phrasal verb for: We need to reach the group.",
      "translation": "Нам нужно догнать группу.",
      "example": "We need to catch up with the group.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 3,
      "donorKey": "catch up with",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-004",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: It's hard to stay current with the latest trends.",
      "options": [
        "keep up with",
        "leave out",
        "drop out of",
        "let in"
      ],
      "answer": "keep up with",
      "explanation": "keep up with is the donor phrasal verb for: It's hard to stay current with the latest trends.",
      "translation": "Трудно успевать за последними тенденциями.",
      "example": "It's hard to keep up with the latest trends.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 4,
      "donorKey": "keep up with",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-005",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: He felt excluded from the team.",
      "options": [
        "leave out",
        "drop out of",
        "let in",
        "get in"
      ],
      "answer": "leave out",
      "explanation": "leave out is the donor phrasal verb for: He felt excluded from the team.",
      "translation": "Он чувствовал себя исключённым из команды.",
      "example": "He felt left out of the team.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 5,
      "donorKey": "leave out",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-006",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: She quit college.",
      "options": [
        "drop out of",
        "let in",
        "get in",
        "dive in"
      ],
      "answer": "drop out of",
      "explanation": "drop out of is the donor phrasal verb for: She quit college.",
      "translation": "Она бросила колледж.",
      "example": "She dropped out of college.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 6,
      "donorKey": "drop out of",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-007",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: You can enter using the spare key.",
      "options": [
        "let in",
        "get in",
        "dive in",
        "check in"
      ],
      "answer": "let in",
      "explanation": "let in is the donor phrasal verb for: You can enter using the spare key.",
      "translation": "Можешь войти сам с запасным ключом.",
      "example": "You can let yourself in with the spare key.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 7,
      "donorKey": "let in",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-008",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: He finally entered after waiting for hours.",
      "options": [
        "get in",
        "dive in",
        "check in",
        "check into"
      ],
      "answer": "get in",
      "explanation": "get in is the donor phrasal verb for: He finally entered after waiting for hours.",
      "translation": "Он наконец вошёл после долгого ожидания.",
      "example": "He finally got in after waiting for hours.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 8,
      "donorKey": "get in",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-009",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: She plunged to save the child.",
      "options": [
        "dive in",
        "check in",
        "check into",
        "walk in"
      ],
      "answer": "dive in",
      "explanation": "dive in is the donor phrasal verb for: She plunged to save the child.",
      "translation": "Она нырнула, чтобы спасти ребёнка.",
      "example": "She dived in to save the child.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 9,
      "donorKey": "dive in",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-010",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: We registered at the hotel.",
      "options": [
        "check in",
        "check into",
        "walk in",
        "go in"
      ],
      "answer": "check in",
      "explanation": "check in is the donor phrasal verb for: We registered at the hotel.",
      "translation": "Мы зарегистрировались в отеле.",
      "example": "We checked in at the hotel.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 10,
      "donorKey": "check in",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-011",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: She registered at a spa for the weekend.",
      "options": [
        "check into",
        "walk in",
        "go in",
        "break in"
      ],
      "answer": "check into",
      "explanation": "check into is the donor phrasal verb for: She registered at a spa for the weekend.",
      "translation": "Она заселилась в спа на выходные.",
      "example": "She checked into a spa for the weekend.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 11,
      "donorKey": "check into",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-012",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: He just entered without knocking.",
      "options": [
        "walk in",
        "go in",
        "break in",
        "lock out"
      ],
      "answer": "walk in",
      "explanation": "walk in is the donor phrasal verb for: He just entered without knocking.",
      "translation": "Он просто вошёл без стука.",
      "example": "He just walked in without knocking.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 12,
      "donorKey": "walk in",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-013",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: Let's enter before it rains.",
      "options": [
        "go in",
        "break in",
        "lock out",
        "walk out"
      ],
      "answer": "go in",
      "explanation": "go in is the donor phrasal verb for: Let's enter before it rains.",
      "translation": "Давай зайдём, пока не пошёл дождь.",
      "example": "Let's go in before it rains.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 13,
      "donorKey": "go in",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-014",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: Someone tried to force their way in last night.",
      "options": [
        "break in",
        "lock out",
        "walk out",
        "climb out"
      ],
      "answer": "break in",
      "explanation": "break in is the donor phrasal verb for: Someone tried to force their way in last night.",
      "translation": "Кто-то пытался взломать дом прошлой ночью.",
      "example": "Someone tried to break in last night.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 14,
      "donorKey": "break in",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-015",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: I couldn't get into my apartment.",
      "options": [
        "lock out",
        "walk out",
        "climb out",
        "look out"
      ],
      "answer": "lock out",
      "explanation": "lock out is the donor phrasal verb for: I couldn't get into my apartment.",
      "translation": "Я не смог попасть в квартиру.",
      "example": "I got locked out of my apartment.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 15,
      "donorKey": "lock out",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-016",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: She got angry and left the meeting.",
      "options": [
        "walk out",
        "climb out",
        "look out",
        "check out"
      ],
      "answer": "walk out",
      "explanation": "walk out is the donor phrasal verb for: She got angry and left the meeting.",
      "translation": "Она рассердилась и вышла с собрания.",
      "example": "She got angry and walked out of the meeting.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 16,
      "donorKey": "walk out",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-017",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: He went through the window to reach the outside.",
      "options": [
        "climb out",
        "look out",
        "check out",
        "drop in"
      ],
      "answer": "climb out",
      "explanation": "climb out is the donor phrasal verb for: He went through the window to reach the outside.",
      "translation": "Он вылез через окно.",
      "example": "He climbed out through the window.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 17,
      "donorKey": "climb out",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-018",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: Be careful! A car is approaching!",
      "options": [
        "look out",
        "check out",
        "drop in",
        "fill out"
      ],
      "answer": "look out",
      "explanation": "look out is the donor phrasal verb for: Be careful! A car is approaching!",
      "translation": "Осторожно! Машина!",
      "example": "Look out! There's a car coming!",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 18,
      "donorKey": "look out",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-019",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: You should try that new cafe.",
      "options": [
        "check out",
        "drop in",
        "fill out",
        "join in"
      ],
      "answer": "check out",
      "explanation": "check out is the donor phrasal verb for: You should try that new cafe.",
      "translation": "Тебе стоит заглянуть в новое кафе.",
      "example": "You should check out that new cafe.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 19,
      "donorKey": "check out",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-020",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: I visited my friend for a chat.",
      "options": [
        "drop in",
        "fill out",
        "join in",
        "fill in for"
      ],
      "answer": "drop in",
      "explanation": "drop in is the donor phrasal verb for: I visited my friend for a chat.",
      "translation": "Я заглянул к другу поболтать.",
      "example": "I dropped in on my friend for a chat.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 20,
      "donorKey": "drop in",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-021",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: Please complete this form.",
      "options": [
        "fill out",
        "join in",
        "fill in for",
        "take in"
      ],
      "answer": "fill out",
      "explanation": "fill out is the donor phrasal verb for: Please complete this form.",
      "translation": "Пожалуйста, заполните эту форму.",
      "example": "Please fill out this form.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 21,
      "donorKey": "fill out",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-022",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: Everyone was singing, so I took part as well.",
      "options": [
        "join in",
        "fill in for",
        "take in",
        "plug in"
      ],
      "answer": "join in",
      "explanation": "join in is the donor phrasal verb for: Everyone was singing, so I took part as well.",
      "translation": "Все пели, и я присоединился.",
      "example": "Everyone was singing, so I joined in.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 22,
      "donorKey": "join in",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-023",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: Can you substitute for me tomorrow?",
      "options": [
        "fill in for",
        "take in",
        "plug in",
        "eat out"
      ],
      "answer": "fill in for",
      "explanation": "fill in for is the donor phrasal verb for: Can you substitute for me tomorrow?",
      "translation": "Можешь подменить меня завтра?",
      "example": "Can you fill in for me tomorrow?",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 23,
      "donorKey": "fill in for",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-024",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: She gave shelter to a stray cat.",
      "options": [
        "take in",
        "plug in",
        "eat out",
        "pull out of"
      ],
      "answer": "take in",
      "explanation": "take in is the donor phrasal verb for: She gave shelter to a stray cat.",
      "translation": "Она приютила бездомного кота.",
      "example": "She took in a stray cat.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 24,
      "donorKey": "take in",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-025",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: Connect the charger to the socket.",
      "options": [
        "plug in",
        "eat out",
        "pull out of",
        "get out"
      ],
      "answer": "plug in",
      "explanation": "plug in is the donor phrasal verb for: Connect the charger to the socket.",
      "translation": "Вставь зарядку в розетку.",
      "example": "Plug in the charger.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 25,
      "donorKey": "plug in",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-026",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: We decided to dine out tonight.",
      "options": [
        "eat out",
        "pull out of",
        "get out",
        "cut out"
      ],
      "answer": "eat out",
      "explanation": "eat out is the donor phrasal verb for: We decided to dine out tonight.",
      "translation": "Мы решили поужинать вне дома.",
      "example": "We decided to eat out tonight.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 26,
      "donorKey": "eat out",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-027",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: He withdrew from the competition.",
      "options": [
        "pull out of",
        "get out",
        "cut out",
        "leave out"
      ],
      "answer": "pull out of",
      "explanation": "pull out of is the donor phrasal verb for: He withdrew from the competition.",
      "translation": "Он выбыл из соревнования.",
      "example": "He pulled out of the competition.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 27,
      "donorKey": "pull out of",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-028",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: Let's leave this place.",
      "options": [
        "get out",
        "cut out",
        "leave out",
        "give up"
      ],
      "answer": "get out",
      "explanation": "get out is the donor phrasal verb for: Let's leave this place.",
      "translation": "Давай уйдём отсюда.",
      "example": "Let's get out of here.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 28,
      "donorKey": "get out",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-029",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: You should eliminate junk food.",
      "options": [
        "cut out",
        "leave out",
        "give up",
        "pick up"
      ],
      "answer": "cut out",
      "explanation": "cut out is the donor phrasal verb for: You should eliminate junk food.",
      "translation": "Тебе стоит исключить вредную еду.",
      "example": "You should cut out junk food.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 29,
      "donorKey": "cut out",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-030",
      "type": "multiple_choice",
      "level": "easy",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: Don't omit any details.",
      "options": [
        "leave out",
        "give up",
        "pick up",
        "catch up with"
      ],
      "answer": "leave out",
      "explanation": "leave out is the donor phrasal verb for: Don't omit any details.",
      "translation": "Не упускай никаких деталей.",
      "example": "Don't leave out any details.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 30,
      "donorKey": "leave out",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-031",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: I want to test this new camera.",
      "options": [
        "try out",
        "turn on",
        "switch off",
        "put on"
      ],
      "answer": "try out",
      "explanation": "try out is the donor phrasal verb for: I want to test this new camera.",
      "translation": "Хочу протестировать новую камеру.",
      "example": "I want to try out this new camera.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 31,
      "donorKey": "try out",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-032",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: Could you switch the light on?",
      "options": [
        "turn on",
        "switch off",
        "put on",
        "go on"
      ],
      "answer": "turn on",
      "explanation": "turn on is the donor phrasal verb for: Could you switch the light on?",
      "translation": "Можешь включить свет?",
      "example": "Could you turn the light on?",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 32,
      "donorKey": "turn on",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-033",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: I turned off my phone.",
      "options": [
        "switch off",
        "put on",
        "go on",
        "call off"
      ],
      "answer": "switch off",
      "explanation": "switch off is the donor phrasal verb for: I turned off my phone.",
      "translation": "Я выключила телефон.",
      "example": "I switched off my phone.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 33,
      "donorKey": "switch off",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-034",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: He started some music.",
      "options": [
        "put on",
        "go on",
        "call off",
        "put off"
      ],
      "answer": "put on",
      "explanation": "put on is the donor phrasal verb for: He started some music.",
      "translation": "Он включил музыку.",
      "example": "He put on some music.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 34,
      "donorKey": "put on",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-035",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: It's raining, let's continue.",
      "options": [
        "go on",
        "call off",
        "put off",
        "put on"
      ],
      "answer": "go on",
      "explanation": "go on is the donor phrasal verb for: It's raining, let's continue.",
      "translation": "Идёт дождь, давай продолжим путь.",
      "example": "It's raining, let's go on.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 35,
      "donorKey": "go on",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-036",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: They canceled the concert.",
      "options": [
        "call off",
        "put off",
        "put on",
        "try on"
      ],
      "answer": "call off",
      "explanation": "call off is the donor phrasal verb for: They canceled the concert.",
      "translation": "Они отменили концерт.",
      "example": "They called off the concert.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 36,
      "donorKey": "call off",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-037",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: The wedding was postponed till June.",
      "options": [
        "put off",
        "put on",
        "try on",
        "take off"
      ],
      "answer": "put off",
      "explanation": "put off is the donor phrasal verb for: The wedding was postponed till June.",
      "translation": "Свадьбу перенесли на июнь.",
      "example": "The wedding was put off till June.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 37,
      "donorKey": "put off",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-038",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: She dressed herself in gloves.",
      "options": [
        "put on",
        "try on",
        "take off",
        "be off"
      ],
      "answer": "put on",
      "explanation": "put on is the donor phrasal verb for: She dressed herself in gloves.",
      "translation": "Она надела перчатки.",
      "example": "She put on her gloves.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 38,
      "donorKey": "put on",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-039",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: I tested how the new jacket fits.",
      "options": [
        "try on",
        "take off",
        "put on",
        "be off"
      ],
      "answer": "try on",
      "explanation": "try on is the donor phrasal verb for: I tested how the new jacket fits.",
      "translation": "Я примерил новую куртку.",
      "example": "I tried on a new jacket.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 39,
      "donorKey": "try on",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-040",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: He removed his glasses.",
      "options": [
        "take off",
        "put on",
        "be off",
        "run off"
      ],
      "answer": "take off",
      "explanation": "take off is the donor phrasal verb for: He removed his glasses.",
      "translation": "Он снял очки.",
      "example": "He took off his glasses.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 40,
      "donorKey": "take off",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-041",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: I've gained some weight.",
      "options": [
        "put on",
        "be off",
        "run off",
        "set off"
      ],
      "answer": "put on",
      "explanation": "put on is the donor phrasal verb for: I've gained some weight.",
      "translation": "Я набрал вес.",
      "example": "I've put on some weight.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 41,
      "donorKey": "put on",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-042",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: I'm leaving for Spain tomorrow.",
      "options": [
        "be off",
        "run off",
        "set off",
        "take off"
      ],
      "answer": "be off",
      "explanation": "be off is the donor phrasal verb for: I'm leaving for Spain tomorrow.",
      "translation": "Я завтра уезжаю в Испанию.",
      "example": "I'm off to Spain tomorrow.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 42,
      "donorKey": "be off",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-043",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: The thief ran away before the police arrived.",
      "options": [
        "run off",
        "set off",
        "take off",
        "see off"
      ],
      "answer": "run off",
      "explanation": "run off is the donor phrasal verb for: The thief ran away before the police arrived.",
      "translation": "Вор убежал до приезда полиции.",
      "example": "The thief ran off before police came.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 43,
      "donorKey": "run off",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-044",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: We set out early to avoid traffic.",
      "options": [
        "set off",
        "take off",
        "see off",
        "go on"
      ],
      "answer": "set off",
      "explanation": "set off is the donor phrasal verb for: We set out early to avoid traffic.",
      "translation": "Мы выехали рано, чтобы избежать пробок.",
      "example": "We set off early to avoid traffic.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 44,
      "donorKey": "set off",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-045",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: The plane departed on time.",
      "options": [
        "take off",
        "see off",
        "go on",
        "carry on"
      ],
      "answer": "take off",
      "explanation": "take off is the donor phrasal verb for: The plane departed on time.",
      "translation": "Самолёт взлетел вовремя.",
      "example": "The plane took off on time.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 45,
      "donorKey": "take off",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-046",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: We went to the airport to see her depart.",
      "options": [
        "see off",
        "go on",
        "carry on",
        "keep on"
      ],
      "answer": "see off",
      "explanation": "see off is the donor phrasal verb for: We went to the airport to see her depart.",
      "translation": "Мы поехали в аэропорт проводить её.",
      "example": "We went to the airport to see her off.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 46,
      "donorKey": "see off",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-047",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: The meeting lasted for hours.",
      "options": [
        "go on",
        "carry on",
        "keep on",
        "get on"
      ],
      "answer": "go on",
      "explanation": "go on is the donor phrasal verb for: The meeting lasted for hours.",
      "translation": "Встреча длилась часами.",
      "example": "The meeting went on for hours.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 47,
      "donorKey": "go on",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-048",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: He continued studying despite problems.",
      "options": [
        "carry on",
        "keep on",
        "get on",
        "get on with"
      ],
      "answer": "carry on",
      "explanation": "carry on is the donor phrasal verb for: He continued studying despite problems.",
      "translation": "Он продолжал учёбу, несмотря на трудности.",
      "example": "He carried on studying despite problems.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 48,
      "donorKey": "carry on",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-049",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: He continues to complain.",
      "options": [
        "keep on",
        "get on",
        "get on with",
        "drop off"
      ],
      "answer": "keep on",
      "explanation": "keep on is the donor phrasal verb for: He continues to complain.",
      "translation": "Он всё жалуется и жалуется.",
      "example": "He keeps on complaining.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 49,
      "donorKey": "keep on",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-050",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: How are you doing at work?",
      "options": [
        "get on",
        "get on with",
        "drop off",
        "finish off"
      ],
      "answer": "get on",
      "explanation": "get on is the donor phrasal verb for: How are you doing at work?",
      "translation": "Как у тебя дела на работе?",
      "example": "How are you getting on at work?",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 50,
      "donorKey": "get on",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-051",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: They don't get along well.",
      "options": [
        "get on",
        "get on with",
        "drop off",
        "finish off"
      ],
      "answer": "get on",
      "explanation": "get on is the donor phrasal verb for: They don't get along well.",
      "translation": "Они не ладят.",
      "example": "They don't get on well.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 51,
      "donorKey": "get on",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-052",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: I must continue with my work.",
      "options": [
        "get on with",
        "drop off",
        "finish off",
        "go off"
      ],
      "answer": "get on with",
      "explanation": "get on with is the donor phrasal verb for: I must continue with my work.",
      "translation": "Мне нужно продолжать работу.",
      "example": "I must get on with my work.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 52,
      "donorKey": "get on with",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-053",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: I dozed off during the movie.",
      "options": [
        "drop off",
        "finish off",
        "go off",
        "put off"
      ],
      "answer": "drop off",
      "explanation": "drop off is the donor phrasal verb for: I dozed off during the movie.",
      "translation": "Я задремал во время фильма.",
      "example": "I dropped off during the movie.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 53,
      "donorKey": "drop off",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-054",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: I'll complete it tomorrow.",
      "options": [
        "finish off",
        "go off",
        "put off",
        "rip off"
      ],
      "answer": "finish off",
      "explanation": "finish off is the donor phrasal verb for: I'll complete it tomorrow.",
      "translation": "Я закончу это завтра.",
      "example": "I'll finish it off tomorrow.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 54,
      "donorKey": "finish off",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-055",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: A bomb exploded in the city.",
      "options": [
        "go off",
        "put off",
        "rip off",
        "show off"
      ],
      "answer": "go off",
      "explanation": "go off is the donor phrasal verb for: A bomb exploded in the city.",
      "translation": "В городе взорвалась бомба.",
      "example": "A bomb went off in the city.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 55,
      "donorKey": "go off",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-056",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: We were discouraged by the queue.",
      "options": [
        "put off",
        "rip off",
        "show off",
        "tell off"
      ],
      "answer": "put off",
      "explanation": "put off is the donor phrasal verb for: We were discouraged by the queue.",
      "translation": "Очередь нас оттолкнула.",
      "example": "We were put off by the queue.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 56,
      "donorKey": "put off",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-057",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: We were overcharged in that store.",
      "options": [
        "rip off",
        "show off",
        "tell off",
        "put up"
      ],
      "answer": "rip off",
      "explanation": "rip off is the donor phrasal verb for: We were overcharged in that store.",
      "translation": "Нас ободрали в этом магазине.",
      "example": "We were ripped off in that store.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 57,
      "donorKey": "rip off",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-058",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: He likes boasting about his car.",
      "options": [
        "show off",
        "tell off",
        "put up",
        "pick up"
      ],
      "answer": "show off",
      "explanation": "show off is the donor phrasal verb for: He likes boasting about his car.",
      "translation": "Он любит хвастаться своей машиной.",
      "example": "He likes showing off his car.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 58,
      "donorKey": "show off",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-059",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: The teacher scolded me for being late.",
      "options": [
        "tell off",
        "put up",
        "pick up",
        "stand up"
      ],
      "answer": "tell off",
      "explanation": "tell off is the donor phrasal verb for: The teacher scolded me for being late.",
      "translation": "Учитель отругал меня за опоздание.",
      "example": "The teacher told me off for being late.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 59,
      "donorKey": "tell off",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-060",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: We installed new shelves.",
      "options": [
        "put up",
        "pick up",
        "stand up",
        "turn up"
      ],
      "answer": "put up",
      "explanation": "put up is the donor phrasal verb for: We installed new shelves.",
      "translation": "Мы повесили новые полки.",
      "example": "We put up new shelves.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 60,
      "donorKey": "put up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-061",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: She lifted the pen from the desk.",
      "options": [
        "pick up",
        "stand up",
        "turn up",
        "take down"
      ],
      "answer": "pick up",
      "explanation": "pick up is the donor phrasal verb for: She lifted the pen from the desk.",
      "translation": "Она подняла ручку.",
      "example": "She picked up the pen.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 61,
      "donorKey": "pick up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-062",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: Everyone rose when he came in.",
      "options": [
        "stand up",
        "turn up",
        "take down",
        "put down"
      ],
      "answer": "stand up",
      "explanation": "stand up is the donor phrasal verb for: Everyone rose when he came in.",
      "translation": "Все встали, когда он вошёл.",
      "example": "Everyone stood up when he entered.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 62,
      "donorKey": "stand up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-063",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: Can you increase the volume?",
      "options": [
        "turn up",
        "take down",
        "put down",
        "bend down"
      ],
      "answer": "turn up",
      "explanation": "turn up is the donor phrasal verb for: Can you increase the volume?",
      "translation": "Можешь сделать громче?",
      "example": "Can you turn up the volume?",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 63,
      "donorKey": "turn up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-064",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: I removed the old posters.",
      "options": [
        "take down",
        "put down",
        "bend down",
        "turn down"
      ],
      "answer": "take down",
      "explanation": "take down is the donor phrasal verb for: I removed the old posters.",
      "translation": "Я снял старые плакаты.",
      "example": "I took down the old posters.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 64,
      "donorKey": "take down",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-065",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: He laid the phone on the table.",
      "options": [
        "put down",
        "bend down",
        "turn down",
        "knock down"
      ],
      "answer": "put down",
      "explanation": "put down is the donor phrasal verb for: He laid the phone on the table.",
      "translation": "Он положил трубку.",
      "example": "He put down the phone.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 65,
      "donorKey": "put down",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-066",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: She leaned forward to tie her shoes.",
      "options": [
        "bend down",
        "turn down",
        "knock down",
        "cut down"
      ],
      "answer": "bend down",
      "explanation": "bend down is the donor phrasal verb for: She leaned forward to tie her shoes.",
      "translation": "Она наклонилась завязать шнурки.",
      "example": "She bent down to tie her shoes.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 66,
      "donorKey": "bend down",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-067",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: Lower the heat; it's too hot.",
      "options": [
        "turn down",
        "knock down",
        "cut down",
        "slow down"
      ],
      "answer": "turn down",
      "explanation": "turn down is the donor phrasal verb for: Lower the heat; it's too hot.",
      "translation": "Убавь температуру, слишком жарко.",
      "example": "Turn down the heat, it's too hot.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 67,
      "donorKey": "turn down",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-068",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: They demolished the old building.",
      "options": [
        "knock down",
        "cut down",
        "slow down",
        "try out"
      ],
      "answer": "knock down",
      "explanation": "knock down is the donor phrasal verb for: They demolished the old building.",
      "translation": "Они снесли старое здание.",
      "example": "They knocked down the old building.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 68,
      "donorKey": "knock down",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-069",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: The tree was felled.",
      "options": [
        "cut down",
        "slow down",
        "try out",
        "turn on"
      ],
      "answer": "cut down",
      "explanation": "cut down is the donor phrasal verb for: The tree was felled.",
      "translation": "Дерево срубили.",
      "example": "The tree was cut down.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 69,
      "donorKey": "cut down",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-070",
      "type": "multiple_choice",
      "level": "medium",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: Slow your speed; you're driving too fast.",
      "options": [
        "slow down",
        "try out",
        "turn on",
        "switch off"
      ],
      "answer": "slow down",
      "explanation": "slow down is the donor phrasal verb for: Slow your speed; you're driving too fast.",
      "translation": "Помедленнее, ты едешь слишком быстро.",
      "example": "Slow down, you're driving too fast.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 70,
      "donorKey": "slow down",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-071",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: They founded a new company.",
      "options": [
        "set up",
        "take up",
        "fix up",
        "grow up"
      ],
      "answer": "set up",
      "explanation": "set up is the donor phrasal verb for: They founded a new company.",
      "translation": "Они основали новую компанию.",
      "example": "They set up a new company.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 71,
      "donorKey": "set up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-072",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: He started painting last year.",
      "options": [
        "take up",
        "fix up",
        "grow up",
        "bring up"
      ],
      "answer": "take up",
      "explanation": "take up is the donor phrasal verb for: He started painting last year.",
      "translation": "Он занялся живописью в прошлом году.",
      "example": "He took up painting last year.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 72,
      "donorKey": "take up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-073",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: We arranged a meeting for Friday.",
      "options": [
        "fix up",
        "grow up",
        "bring up",
        "tidy up"
      ],
      "answer": "fix up",
      "explanation": "fix up is the donor phrasal verb for: We arranged a meeting for Friday.",
      "translation": "Мы назначили встречу на пятницу.",
      "example": "We fixed up a meeting for Friday.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 73,
      "donorKey": "fix up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-074",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: I was raised in a small town.",
      "options": [
        "grow up",
        "bring up",
        "tidy up",
        "wash up"
      ],
      "answer": "grow up",
      "explanation": "grow up is the donor phrasal verb for: I was raised in a small town.",
      "translation": "Я вырос в маленьком городе.",
      "example": "I grew up in a small town.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 74,
      "donorKey": "grow up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-075",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: Her grandparents raised her.",
      "options": [
        "bring up",
        "tidy up",
        "wash up",
        "end up"
      ],
      "answer": "bring up",
      "explanation": "bring up is the donor phrasal verb for: Her grandparents raised her.",
      "translation": "Её воспитали бабушка и дедушка.",
      "example": "She was brought up by her grandparents.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 75,
      "donorKey": "bring up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-076",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: Let's clean the room.",
      "options": [
        "tidy up",
        "wash up",
        "end up",
        "give up"
      ],
      "answer": "tidy up",
      "explanation": "tidy up is the donor phrasal verb for: Let's clean the room.",
      "translation": "Давай приберёмся в комнате.",
      "example": "Let's tidy up the room.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 76,
      "donorKey": "tidy up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-077",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: I hate doing the dishes.",
      "options": [
        "wash up",
        "end up",
        "give up",
        "make up"
      ],
      "answer": "wash up",
      "explanation": "wash up is the donor phrasal verb for: I hate doing the dishes.",
      "translation": "Я ненавижу мыть посуду.",
      "example": "I hate washing up.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 77,
      "donorKey": "wash up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-078",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: We eventually stayed at a motel.",
      "options": [
        "end up",
        "give up",
        "make up",
        "be made up of"
      ],
      "answer": "end up",
      "explanation": "end up is the donor phrasal verb for: We eventually stayed at a motel.",
      "translation": "В итоге мы остановились в мотеле.",
      "example": "We ended up staying at a motel.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 78,
      "donorKey": "end up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-079",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: Don't lose heart; you can do it!",
      "options": [
        "give up",
        "make up",
        "be made up of",
        "take up"
      ],
      "answer": "give up",
      "explanation": "give up is the donor phrasal verb for: Don't lose heart; you can do it!",
      "translation": "Не сдавайся, у тебя получится!",
      "example": "Don't give up, you can do it!",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 79,
      "donorKey": "give up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-080",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: Children constitute half of the class.",
      "options": [
        "make up",
        "be made up of",
        "take up",
        "turn up"
      ],
      "answer": "make up",
      "explanation": "make up is the donor phrasal verb for: Children constitute half of the class.",
      "translation": "Дети составляют половину класса.",
      "example": "Children make up half of the class.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 80,
      "donorKey": "make up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-081",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: The human body consists of cells.",
      "options": [
        "be made up of",
        "take up",
        "turn up",
        "use up"
      ],
      "answer": "be made up of",
      "explanation": "be made up of is the donor phrasal verb for: The human body consists of cells.",
      "translation": "Человеческое тело состоит из клеток.",
      "example": "The human body is made up of cells.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 81,
      "donorKey": "be made up of",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-082",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: This sofa occupies too much space.",
      "options": [
        "take up",
        "turn up",
        "use up",
        "bring up"
      ],
      "answer": "take up",
      "explanation": "take up is the donor phrasal verb for: This sofa occupies too much space.",
      "translation": "Этот диван занимает слишком много места.",
      "example": "This sofa takes up too much space.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 82,
      "donorKey": "take up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-083",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: He didn't show up for the meeting.",
      "options": [
        "turn up",
        "use up",
        "bring up",
        "come up"
      ],
      "answer": "turn up",
      "explanation": "turn up is the donor phrasal verb for: He didn't show up for the meeting.",
      "translation": "Он не появился на встрече.",
      "example": "He didn't turn up for the meeting.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 83,
      "donorKey": "turn up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-084",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: I've consumed all the milk.",
      "options": [
        "use up",
        "bring up",
        "come up",
        "come up with"
      ],
      "answer": "use up",
      "explanation": "use up is the donor phrasal verb for: I've consumed all the milk.",
      "translation": "Я израсходовал всё молоко.",
      "example": "I've used up all the milk.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 84,
      "donorKey": "use up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-085",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: Don't mention that topic again.",
      "options": [
        "bring up",
        "come up",
        "come up with",
        "make up"
      ],
      "answer": "bring up",
      "explanation": "bring up is the donor phrasal verb for: Don't mention that topic again.",
      "translation": "Не поднимай эту тему снова.",
      "example": "Don't bring up that topic again.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 85,
      "donorKey": "bring up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-086",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: The issue arose in conversation.",
      "options": [
        "come up",
        "come up with",
        "make up",
        "cheer up"
      ],
      "answer": "come up",
      "explanation": "come up is the donor phrasal verb for: The issue arose in conversation.",
      "translation": "Этот вопрос всплыл в разговоре.",
      "example": "The issue came up in conversation.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 86,
      "donorKey": "come up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-087",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: She invented a great idea.",
      "options": [
        "come up with",
        "make up",
        "cheer up",
        "save up"
      ],
      "answer": "come up with",
      "explanation": "come up with is the donor phrasal verb for: She invented a great idea.",
      "translation": "Она придумала отличную идею.",
      "example": "She came up with a great idea.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 87,
      "donorKey": "come up with",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-088",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: He invented the whole story.",
      "options": [
        "make up",
        "cheer up",
        "save up",
        "clear up"
      ],
      "answer": "make up",
      "explanation": "make up is the donor phrasal verb for: He invented the whole story.",
      "translation": "Он всё это выдумал.",
      "example": "He made the whole story up.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 88,
      "donorKey": "make up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-089",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: Be more positive; things will get better.",
      "options": [
        "cheer up",
        "save up",
        "clear up",
        "blow up"
      ],
      "answer": "cheer up",
      "explanation": "cheer up is the donor phrasal verb for: Be more positive; things will get better.",
      "translation": "Не унывай, всё наладится.",
      "example": "Cheer up, things will get better.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 89,
      "donorKey": "cheer up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-090",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: I'm setting money aside for a car.",
      "options": [
        "save up",
        "clear up",
        "blow up",
        "tear up"
      ],
      "answer": "save up",
      "explanation": "save up is the donor phrasal verb for: I'm setting money aside for a car.",
      "translation": "Я коплю на машину.",
      "example": "I'm saving up for a car.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 90,
      "donorKey": "save up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-091",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: It cleared by afternoon.",
      "options": [
        "clear up",
        "blow up",
        "tear up",
        "beat up"
      ],
      "answer": "clear up",
      "explanation": "clear up is the donor phrasal verb for: It cleared by afternoon.",
      "translation": "К полудню прояснилось.",
      "example": "It cleared up by afternoon.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 91,
      "donorKey": "clear up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-092",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: The engine suddenly exploded.",
      "options": [
        "blow up",
        "tear up",
        "beat up",
        "break up"
      ],
      "answer": "blow up",
      "explanation": "blow up is the donor phrasal verb for: The engine suddenly exploded.",
      "translation": "Двигатель внезапно взорвался.",
      "example": "The engine blew up suddenly.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 92,
      "donorKey": "blow up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-093",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: She ripped the letter apart.",
      "options": [
        "tear up",
        "beat up",
        "break up",
        "do up"
      ],
      "answer": "tear up",
      "explanation": "tear up is the donor phrasal verb for: She ripped the letter apart.",
      "translation": "Она разорвала письмо.",
      "example": "She tore up the letter.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 93,
      "donorKey": "tear up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-094",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: He was attacked by a gang.",
      "options": [
        "beat up",
        "break up",
        "do up",
        "look up"
      ],
      "answer": "beat up",
      "explanation": "beat up is the donor phrasal verb for: He was attacked by a gang.",
      "translation": "Его избила банда.",
      "example": "He was beaten up by a gang.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 94,
      "donorKey": "beat up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-095",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: They separated last year.",
      "options": [
        "break up",
        "do up",
        "look up",
        "put up with"
      ],
      "answer": "break up",
      "explanation": "break up is the donor phrasal verb for: They separated last year.",
      "translation": "Они расстались в прошлом году.",
      "example": "They broke up last year.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 95,
      "donorKey": "break up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-096",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: Fasten your coat; it's cold.",
      "options": [
        "do up",
        "look up",
        "put up with",
        "hold up"
      ],
      "answer": "do up",
      "explanation": "do up is the donor phrasal verb for: Fasten your coat; it's cold.",
      "translation": "Застегни пальто, холодно.",
      "example": "Do up your coat, it's cold.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 96,
      "donorKey": "do up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-097",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: They renovated their kitchen.",
      "options": [
        "do up",
        "look up",
        "put up with",
        "hold up"
      ],
      "answer": "do up",
      "explanation": "do up is the donor phrasal verb for: They renovated their kitchen.",
      "translation": "Они отремонтировали кухню.",
      "example": "They did up their kitchen.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 97,
      "donorKey": "do up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-098",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: Find it in the dictionary.",
      "options": [
        "look up",
        "put up with",
        "hold up",
        "set up"
      ],
      "answer": "look up",
      "explanation": "look up is the donor phrasal verb for: Find it in the dictionary.",
      "translation": "Посмотри это в словаре.",
      "example": "Look it up in the dictionary.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 98,
      "donorKey": "look up",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-099",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: I can't tolerate his behavior.",
      "options": [
        "put up with",
        "hold up",
        "set up",
        "take up"
      ],
      "answer": "put up with",
      "explanation": "put up with is the donor phrasal verb for: I can't tolerate his behavior.",
      "translation": "Я не могу терпеть его поведение.",
      "example": "I can't put up with his behavior.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 99,
      "donorKey": "put up with",
      "shuffleOptions": true
    },
    {
      "id": "phrasal-verbs-100",
      "type": "multiple_choice",
      "level": "hard",
      "topic": "donor-import",
      "prompt": "Which phrasal verb best expresses this meaning: Sorry for delaying you.",
      "options": [
        "hold up",
        "set up",
        "take up",
        "fix up"
      ],
      "answer": "hold up",
      "explanation": "hold up is the donor phrasal verb for: Sorry for delaying you.",
      "translation": "Извини, что задержал тебя.",
      "example": "Sorry for holding you up.",
      "source": "donor/PhrasalVerbsQuiz-index.html DATA",
      "donorEntry": 100,
      "donorKey": "hold up",
      "shuffleOptions": true
    }
  ],
};
